/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SondageRouteImport } from './routes/sondage'
import { Route as AccueilRouteImport } from './routes/accueil'
import { Route as IndexRouteImport } from './routes/index'

const SondageRoute = SondageRouteImport.update({
  id: '/sondage',
  path: '/sondage',
  getParentRoute: () => rootRouteImport,
} as any)
const AccueilRoute = AccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/sondage': typeof SondageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/sondage': typeof SondageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/sondage': typeof SondageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/accueil' | '/sondage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accueil' | '/sondage'
  id: '__root__' | '/' | '/accueil' | '/sondage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccueilRoute: typeof AccueilRoute
  SondageRoute: typeof SondageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sondage': {
      id: '/sondage'
      path: '/sondage'
      fullPath: '/sondage'
      preLoaderRoute: typeof SondageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accueil': {
      id: '/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AccueilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccueilRoute: AccueilRoute,
  SondageRoute: SondageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
